services:
  monica-proxy:
    build:
      context: .
      dockerfile: Dockerfile
    image: monica-proxy
    container_name: monica-proxy
    restart: unless-stopped
    command: ["./monica"]
    environment:
      - MONICA_COOKIE=${MONICA_COOKIE}

  nginx:
    image: nginx:latest
    container_name: monica-nginx
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - monica-proxy